# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScmCli < Formula
  desc "SCM-Manager CLI Client"
  homepage "https://scm-manager.org/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/0.1.0/scm-cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "8abf89511e973a70e06ceea5ef3f24c9a8ea546d1d4ecb44fa93494188fbb567"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/0.1.0/scm-cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "645deb73deb769187f0bd9843b72de625ef0da00072169a03452e6bf5084cdaf"

      def install
        bin.install "scm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/0.1.0/scm-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "2d2a38992b14acaa2098bf1ccd7ba6952a7b05797832e74d22b2da8dd4021cb2"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/0.1.0/scm-cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "f215033deb7acf2de0ee2383f53b0269710b90ab47eb0dd223652121e2b61e17"

      def install
        bin.install "scm"
      end
    end
  end
end
