# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScmCli < Formula
  desc "SCM-Manager CLI Client"
  homepage "https://scm-manager.org/cli"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/1.0.2/scm-cli_1.0.2_Darwin_arm64.tar.gz"
      sha256 "0493183f78520b7d91ba9a45c212e1b0fd4751a4ec9b0802bb18f37e9aed669b"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.intel?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/1.0.2/scm-cli_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "9ea066b87609a3de9bb69618a220bcebc9025e8bbf6582483a0299c1184c0f47"

      def install
        bin.install "scm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/1.0.2/scm-cli_1.0.2_Linux_x86_64.tar.gz"
      sha256 "f6cac1cae52f3f51016550f279445b1b36584071558aca6cf2308229ce5f9071"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://packages.scm-manager.org/repository/scm-cli-releases/1.0.2/scm-cli_1.0.2_Linux_arm64.tar.gz"
      sha256 "6647800abf2c887d7581f53d7ce60bfb373fb36bfec1abbde3921199f42cd173"

      def install
        bin.install "scm"
      end
    end
  end
end
